#numeric data types
#int: whole numbers
age = 25
height = 170
#float: decimal numbers
weight = 70.5
#complex: numbers with real and imaginary parts
complex_number = 2 + 3j

#Logical data type
#boolean data type
#bool: represents True or False values
is_student = True
is_employed = False
#Nonetype
#None: represents the absence of a value or a null value
result = None #it is like declaring a variable without initializing it with any value, it is used to indicate that the variable has no value or is not yet assigned a value

#sequence data types
#str: represents a sequence of characters
name = "Vishal" #string can be defined using single quotes('') or double quotes("") or triple quotes(''' ''') or (""" """)

#list: represents an ordered collection of items which can be of different types
# list is mutable (can be changed after creation) and it can contain duplicate values
numbers = [1, 2, 3, 4, 5]
fruits = ["apple", "banana", "cherry"]   

#tuple: represents an ordered collection of items which can be of different types but is immutable (cannot be changed after creation)
#the difference between list and tuple is that list is mutable and tuple is immutable
coordinates = (10, 20) #tuple is defined using parentheses() 

#range: represents a sequence of numbers generated by a start, stop and step value
#range is immutable and it is defined using the range() function
numbers_range = range(1, 10, 2) #range(start, stop, step) start is inclusive and stop is exclusive and step is the difference between each number in the sequence

# to find the data type of a variable we can use the type() function
print(type(age))  # <class 'int'>
print(type(weight))  # <class 'float'>
print(type(complex_number))  # <class 'complex'>
print(type(is_student))  # <class 'bool'>
print(type(result))  # <class 'NoneType'>
print(type(name))  # <class 'str'>
print(type(numbers))  # <class 'list'>
print(type(coordinates))  # <class 'tuple'>
print(type(numbers_range))  # <class 'range'>

#another is Set: represents an unordered collection of unique items which can be of different types
# set is mutable and it is defined using curly braces{} or the set() function
unique_numbers = {1, 2, 3, 4, 5}
unique_numbers1={1, 2, 3, 4, 5, 5} #duplicate values will be removed in set
unique_numbers2=set([1, 2, 3, 4, 5])
print(type(unique_numbers), type(unique_numbers1), type(unique_numbers2))  # <class 'set'>
print(unique_numbers)  # {1, 2, 3, 4, 5}
print(unique_numbers1)  # {1, 2, 3, 4, 5}
print(unique_numbers2)  # {1, 2, 3, 4, 5}

#another type of set is frozenset: 
# the elements can be of different types but it is immutable (cannot be changed after creation)
# just like set it also doesnt allow duplicate values
# frozenset is defined using the frozenset() function only and it is immutable

immutable_set = frozenset([1, 2, 3, 4, 5])

#MAPPING DATA TYPE
#dict: represents a collection of key-value pairs where each key is unique and maps to a value
#it is mutable
#defined by{} or the dict() function
#syntax: dict_name = {key1: value1, key2: value2, ...}
person = {"name": "Vishal", "age": 25, "city": "New York"}
person1 = dict(name="Vishal", age=25, city="New York")
print(type(person), type(person1))  # <class 'dict'>
print(person)  # {'name': 'Vishal', 'age': 25, 'city': 'New York'}